// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/litixsoft/lxgo/crypt (interfaces: ICrypt)

// Package lxCryptMocks is a generated GoMock package.
package lxCryptMocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockICrypt is a mock of ICrypt interface
type MockICrypt struct {
	ctrl     *gomock.Controller
	recorder *MockICryptMockRecorder
}

// MockICryptMockRecorder is the mock recorder for MockICrypt
type MockICryptMockRecorder struct {
	mock *MockICrypt
}

// NewMockICrypt creates a new mock instance
func NewMockICrypt(ctrl *gomock.Controller) *MockICrypt {
	mock := &MockICrypt{ctrl: ctrl}
	mock.recorder = &MockICryptMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockICrypt) EXPECT() *MockICryptMockRecorder {
	return m.recorder
}

// ComparePassword mocks base method
func (m *MockICrypt) ComparePassword(arg0, arg1 string) error {
	ret := m.ctrl.Call(m, "ComparePassword", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ComparePassword indicates an expected call of ComparePassword
func (mr *MockICryptMockRecorder) ComparePassword(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComparePassword", reflect.TypeOf((*MockICrypt)(nil).ComparePassword), arg0, arg1)
}

// GeneratePassword mocks base method
func (m *MockICrypt) GeneratePassword(arg0 string) (string, error) {
	ret := m.ctrl.Call(m, "GeneratePassword", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePassword indicates an expected call of GeneratePassword
func (mr *MockICryptMockRecorder) GeneratePassword(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePassword", reflect.TypeOf((*MockICrypt)(nil).GeneratePassword), arg0)
}
