sudo: required

services:
- docker

-language: go

before_install:
  - docker pull golang:1.11
  - docker pull mongo:4.0

script:
  - docker-compose -f ./build/compose.test.yaml build
  - docker-compose -f ./build/compose.test.yaml run lxgo
  - docker-compose -f ./build/compose.test.yaml down
