sudo: required
notifications:
  webhooks: https://outlook.office.com/webhook/64112b37-462c-4c47-a980-d4e030e48b68@6c6c46b4-fb1d-475e-8011-684739c7ca7e/TravisCI/dc9dd3b15b6a4fcabf5a43a28da6011d/249c6ecb-24f4-45ee-a889-436388713e0a

services:
- docker

-language: go

before_install:
  - docker pull golang:1.12
  - docker pull mongo:4.0

script:
  - docker-compose -f ./compose.test.yaml build
  - docker-compose -f ./compose.test.yaml run lxgo
  - docker-compose -f ./compose.test.yaml down
