sudo: required
notifications:
  webhooks: https://outlook.office.com/webhook/a4f703e7-a5de-4bce-9ce2-c59511226eac@6c6c46b4-fb1d-475e-8011-684739c7ca7e/JenkinsCI/5022d431c40d48d08761994228b1086a/249c6ecb-24f4-45ee-a889-436388713e0a

services:
- docker

-language: go

before_install:
  - docker pull golang:1.12
  - docker pull mongo:4.0

script:
  - docker-compose -f ./compose.test.yaml build
  - docker-compose -f ./compose.test.yaml run lxgo
  - docker-compose -f ./compose.test.yaml down
