// Code generated by MockGen. DO NOT EDIT.
// Source: db/db.go

// Package lxDbMocks is a generated GoMock package.
package lxDbMocks

import (
	gomock "github.com/golang/mock/gomock"
	lxDb "github.com/litixsoft/lxgo/db"
	reflect "reflect"
	time "time"
)

// MockIBaseRepo is a mock of IBaseRepo interface
type MockIBaseRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIBaseRepoMockRecorder
}

// MockIBaseRepoMockRecorder is the mock recorder for MockIBaseRepo
type MockIBaseRepoMockRecorder struct {
	mock *MockIBaseRepo
}

// NewMockIBaseRepo creates a new mock instance
func NewMockIBaseRepo(ctrl *gomock.Controller) *MockIBaseRepo {
	mock := &MockIBaseRepo{ctrl: ctrl}
	mock.recorder = &MockIBaseRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIBaseRepo) EXPECT() *MockIBaseRepoMockRecorder {
	return m.recorder
}

// CreateIndexes mocks base method
func (m *MockIBaseRepo) CreateIndexes(indexes interface{}, args ...interface{}) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{indexes}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateIndexes", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIndexes indicates an expected call of CreateIndexes
func (mr *MockIBaseRepoMockRecorder) CreateIndexes(indexes interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{indexes}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIndexes", reflect.TypeOf((*MockIBaseRepo)(nil).CreateIndexes), varargs...)
}

// InsertOne mocks base method
func (m *MockIBaseRepo) InsertOne(doc interface{}, args ...interface{}) (interface{}, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{doc}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InsertOne", varargs...)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOne indicates an expected call of InsertOne
func (mr *MockIBaseRepoMockRecorder) InsertOne(doc interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{doc}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOne", reflect.TypeOf((*MockIBaseRepo)(nil).InsertOne), varargs...)
}

// InsertMany mocks base method
func (m *MockIBaseRepo) InsertMany(docs []interface{}, args ...interface{}) (*lxDb.InsertManyResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{docs}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InsertMany", varargs...)
	ret0, _ := ret[0].(*lxDb.InsertManyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertMany indicates an expected call of InsertMany
func (mr *MockIBaseRepoMockRecorder) InsertMany(docs interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{docs}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMany", reflect.TypeOf((*MockIBaseRepo)(nil).InsertMany), varargs...)
}

// CountDocuments mocks base method
func (m *MockIBaseRepo) CountDocuments(filter interface{}, args ...interface{}) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{filter}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CountDocuments", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDocuments indicates an expected call of CountDocuments
func (mr *MockIBaseRepoMockRecorder) CountDocuments(filter interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{filter}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDocuments", reflect.TypeOf((*MockIBaseRepo)(nil).CountDocuments), varargs...)
}

// EstimatedDocumentCount mocks base method
func (m *MockIBaseRepo) EstimatedDocumentCount(args ...interface{}) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EstimatedDocumentCount", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimatedDocumentCount indicates an expected call of EstimatedDocumentCount
func (mr *MockIBaseRepoMockRecorder) EstimatedDocumentCount(args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimatedDocumentCount", reflect.TypeOf((*MockIBaseRepo)(nil).EstimatedDocumentCount), args...)
}

// Find mocks base method
func (m *MockIBaseRepo) Find(filter, result interface{}, args ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{filter, result}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Find indicates an expected call of Find
func (mr *MockIBaseRepoMockRecorder) Find(filter, result interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{filter, result}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIBaseRepo)(nil).Find), varargs...)
}

// FindOne mocks base method
func (m *MockIBaseRepo) FindOne(filter, result interface{}, args ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{filter, result}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOne", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindOne indicates an expected call of FindOne
func (mr *MockIBaseRepoMockRecorder) FindOne(filter, result interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{filter, result}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockIBaseRepo)(nil).FindOne), varargs...)
}

// FindOneAndDelete mocks base method
func (m *MockIBaseRepo) FindOneAndDelete(filter, result interface{}, args ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{filter, result}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOneAndDelete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindOneAndDelete indicates an expected call of FindOneAndDelete
func (mr *MockIBaseRepoMockRecorder) FindOneAndDelete(filter, result interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{filter, result}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneAndDelete", reflect.TypeOf((*MockIBaseRepo)(nil).FindOneAndDelete), varargs...)
}

// FindOneAndReplace mocks base method
func (m *MockIBaseRepo) FindOneAndReplace(filter, replacement, result interface{}, args ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{filter, replacement, result}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOneAndReplace", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindOneAndReplace indicates an expected call of FindOneAndReplace
func (mr *MockIBaseRepoMockRecorder) FindOneAndReplace(filter, replacement, result interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{filter, replacement, result}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneAndReplace", reflect.TypeOf((*MockIBaseRepo)(nil).FindOneAndReplace), varargs...)
}

// FindOneAndUpdate mocks base method
func (m *MockIBaseRepo) FindOneAndUpdate(filter, update, result interface{}, args ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{filter, update, result}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOneAndUpdate", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindOneAndUpdate indicates an expected call of FindOneAndUpdate
func (mr *MockIBaseRepoMockRecorder) FindOneAndUpdate(filter, update, result interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{filter, update, result}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneAndUpdate", reflect.TypeOf((*MockIBaseRepo)(nil).FindOneAndUpdate), varargs...)
}

// UpdateOne mocks base method
func (m *MockIBaseRepo) UpdateOne(filter, update interface{}, args ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{filter, update}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateOne", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOne indicates an expected call of UpdateOne
func (mr *MockIBaseRepoMockRecorder) UpdateOne(filter, update interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{filter, update}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOne", reflect.TypeOf((*MockIBaseRepo)(nil).UpdateOne), varargs...)
}

// UpdateMany mocks base method
func (m *MockIBaseRepo) UpdateMany(filter, update interface{}, args ...interface{}) (*lxDb.UpdateManyResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{filter, update}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateMany", varargs...)
	ret0, _ := ret[0].(*lxDb.UpdateManyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMany indicates an expected call of UpdateMany
func (mr *MockIBaseRepoMockRecorder) UpdateMany(filter, update interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{filter, update}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMany", reflect.TypeOf((*MockIBaseRepo)(nil).UpdateMany), varargs...)
}

// DeleteOne mocks base method
func (m *MockIBaseRepo) DeleteOne(filter interface{}, args ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{filter}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteOne", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOne indicates an expected call of DeleteOne
func (mr *MockIBaseRepoMockRecorder) DeleteOne(filter interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{filter}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOne", reflect.TypeOf((*MockIBaseRepo)(nil).DeleteOne), varargs...)
}

// DeleteMany mocks base method
func (m *MockIBaseRepo) DeleteMany(filter interface{}, args ...interface{}) (*lxDb.DeleteManyResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{filter}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteMany", varargs...)
	ret0, _ := ret[0].(*lxDb.DeleteManyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMany indicates an expected call of DeleteMany
func (mr *MockIBaseRepoMockRecorder) DeleteMany(filter interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{filter}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMany", reflect.TypeOf((*MockIBaseRepo)(nil).DeleteMany), varargs...)
}

// GetCollection mocks base method
func (m *MockIBaseRepo) GetCollection() interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollection")
	ret0, _ := ret[0].(interface{})
	return ret0
}

// GetCollection indicates an expected call of GetCollection
func (mr *MockIBaseRepoMockRecorder) GetCollection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollection", reflect.TypeOf((*MockIBaseRepo)(nil).GetCollection))
}

// GetDb mocks base method
func (m *MockIBaseRepo) GetDb() interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDb")
	ret0, _ := ret[0].(interface{})
	return ret0
}

// GetDb indicates an expected call of GetDb
func (mr *MockIBaseRepoMockRecorder) GetDb() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDb", reflect.TypeOf((*MockIBaseRepo)(nil).GetDb))
}

// GetRepoName mocks base method
func (m *MockIBaseRepo) GetRepoName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepoName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRepoName indicates an expected call of GetRepoName
func (mr *MockIBaseRepoMockRecorder) GetRepoName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepoName", reflect.TypeOf((*MockIBaseRepo)(nil).GetRepoName))
}

// MockIBaseRepoAudit is a mock of IBaseRepoAudit interface
type MockIBaseRepoAudit struct {
	ctrl     *gomock.Controller
	recorder *MockIBaseRepoAuditMockRecorder
}

// MockIBaseRepoAuditMockRecorder is the mock recorder for MockIBaseRepoAudit
type MockIBaseRepoAuditMockRecorder struct {
	mock *MockIBaseRepoAudit
}

// NewMockIBaseRepoAudit creates a new mock instance
func NewMockIBaseRepoAudit(ctrl *gomock.Controller) *MockIBaseRepoAudit {
	mock := &MockIBaseRepoAudit{ctrl: ctrl}
	mock.recorder = &MockIBaseRepoAuditMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIBaseRepoAudit) EXPECT() *MockIBaseRepoAuditMockRecorder {
	return m.recorder
}

// LogEntry mocks base method
func (m *MockIBaseRepoAudit) LogEntry(action string, user, data interface{}, timeout ...time.Duration) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{action, user, data}
	for _, a := range timeout {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LogEntry", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogEntry indicates an expected call of LogEntry
func (mr *MockIBaseRepoAuditMockRecorder) LogEntry(action, user, data interface{}, timeout ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{action, user, data}, timeout...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogEntry", reflect.TypeOf((*MockIBaseRepoAudit)(nil).LogEntry), varargs...)
}

// LogEntries mocks base method
func (m *MockIBaseRepoAudit) LogEntries(entries []interface{}, timeout ...time.Duration) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{entries}
	for _, a := range timeout {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LogEntries", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogEntries indicates an expected call of LogEntries
func (mr *MockIBaseRepoAuditMockRecorder) LogEntries(entries interface{}, timeout ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{entries}, timeout...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogEntries", reflect.TypeOf((*MockIBaseRepoAudit)(nil).LogEntries), varargs...)
}
